# Generated by Django 4.2 on 2026-01-10 17:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('image_url', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('min_players', models.IntegerField(default=2)),
                ('max_players', models.IntegerField(default=2)),
            ],
            options={
                'db_table': 'games',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('code', models.CharField(max_length=4, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.CharField(max_length=8)),
                ('selected_game', models.CharField(blank=True, max_length=50, null=True)),
                ('rounds', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('status', models.CharField(default='waiting', max_length=20)),
                ('max_players', models.IntegerField(default=2)),
            ],
            options={
                'db_table': 'rooms',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=8)),
                ('content', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('message_type', models.CharField(choices=[('chat', 'Chat'), ('voice', 'Voice'), ('image', 'Image'), ('system', 'System'), ('notification', 'Notification')], default='chat', max_length=20)),
                ('voice_url', models.CharField(blank=True, max_length=500, null=True)),
                ('voice_duration', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(60)])),
                ('image_url', models.CharField(blank=True, max_length=500, null=True)),
                ('image_width', models.IntegerField(blank=True, null=True)),
                ('image_height', models.IntegerField(blank=True, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='rooms.room')),
            ],
            options={
                'db_table': 'messages',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_round', models.IntegerField(default=1)),
                ('total_rounds', models.IntegerField(default=1)),
                ('player1_score', models.IntegerField(default=0)),
                ('player2_score', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('winner', models.CharField(blank=True, max_length=8, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed')], default='active', max_length=20)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.game')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_sessions', to='rooms.room')),
            ],
            options={
                'db_table': 'game_sessions',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=8)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6)),
                ('avatar', models.CharField(default='👨', max_length=10)),
                ('is_ready', models.BooleanField(default=False)),
                ('is_owner', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('is_online', models.BooleanField(default=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='rooms.room')),
            ],
            options={
                'db_table': 'players',
                'unique_together': {('room', 'username')},
            },
        ),
        migrations.CreateModel(
            name='MessageReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=8)),
                ('emoji', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='rooms.message')),
            ],
            options={
                'db_table': 'message_reactions',
                'unique_together': {('message', 'user', 'emoji')},
            },
        ),
    ]
