# Generated by Django 4.2 on 2026-02-09 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('image_url', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('min_players', models.IntegerField(default=2)),
                ('max_players', models.IntegerField(default=2)),
            ],
            options={
                'db_table': 'games',
            },
        ),
    ]
